config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'urls/create'
  get 'urls/new'
  get 'urls/index'
  devise_for :users
  root to: 'scraps#new'
  get 'scrapping', to: 'pages#scrapping'
  resources :properties, only: [ :index, :create ]
  resources :scraps
  resources :urls, only: [ :new, :create, :index ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  validates :ref, uniqueness: { scope: :date }
  belongs_to :scrap
end

app/models/scrap.rb
class Scrap < ApplicationRecord
  validates :scrap_url, presence: true, :url => true
  has_many :properties, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :scraps

  # for ActiveAdmin
  def name
    "#{id} - #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
require 'open-uri'
require 'nokogiri'


class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

end

app/controllers/properties_controller.rb
require 'open-uri'
require 'nokogiri'

class PropertiesController < ApplicationController
  before_action :scrap_params

  # def new
  # end

  def create
    urls = scrap_params
    raise
    urls.each do |url|
      html_file = open(url).read
      html_doc = Nokogiri::HTML(html_file)
      price = html_doc.search(".item-price").text.strip
      html_doc.search(".item-price").remove
      title = html_doc.search('.item-title').text.strip
      phone = html_doc.at('.txt-indigo').text.strip if html_doc.at('.txt-indigo')
      full_city = html_doc.search(".margin-bottom-8").text.strip
      full_date = html_doc.search(".item-date").text.strip
      reference = full_date[11, 5]
      date = full_date[19...full_date.length].to_date
      @property = Property.create(price: price, title: title, phone: phone, ref: reference, date: date, url: url, city: full_city)
    end
    redirect_to properties_path
  end

  def index
    @properties = Property.all
  end
end

private

def scrap_params
  params.permit(:urls)
end

app/controllers/scraps_controller.rb
require 'open-uri'
require 'nokogiri'

class ScrapsController < ApplicationController

  def new
    @scrap = Scrap.new
  end

  def create
    @scrap = Scrap.new(scrap_params)
    @scrap.user_id = current_user.id
    if @scrap.save
      scrapping(@scrap.scrap_url)
      parsing(@urls, @scrap)
      redirect_to scrap_path(@scrap, @properties)
    else
      redirect_to root_path
    end
  end

  def show
    @scrap = Scrap.find(params[:id])
    @properties = Property.where(scrap_id: @scrap.id)
    @scrap.update(city: @properties.last.city, number: @properties.length) unless @properties.empty?
  end

  def index
    @scraps = Scrap.where(user_id: current_user)
  end

  private

  def scrap_params
    params.require(:scrap).permit(:scrap_url)
  end

  def scrapping(url)
    @urls = []
    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)
    html_doc.search('.item-title').each do |element|
      element.text.strip
      mini_url = element.attribute('href').value
      full_url = "https://www.pap.fr#{mini_url}"
      @urls << full_url
    end
  end

  def parsing(urls, scrap)
    urls.each do |url|
      html_file = open(url).read
      html_doc = Nokogiri::HTML(html_file)
      price = html_doc.search(".item-price").text.strip
      html_doc.search(".item-price").remove
      title = html_doc.search('.item-title').text.strip
      phone = html_doc.at('.txt-indigo').text.strip if html_doc.at('.txt-indigo')
      full_city = html_doc.search(".margin-bottom-8").text.strip
      full_date = html_doc.search(".item-date").text.strip
      reference = full_date[11, 5]
      string_date = full_date[19...full_date.length]
      date = Date.parse(string_date) rescue nil
      @property = Property.create(price: price, title: title, phone: phone, ref: reference, date: date, url: url, city: full_city, scrap_id: @scrap.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,90,146,0.3) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "banner-home.jpg" %>);">
  <div class="banner-content">
    <h1>Scrap me !</h1>
    <p>Get in touch with owners quickly</p>
    <%= form_tag properties_path, method: :post, class: "form-inline form-home" do %>
      <%= text_field_tag :url_input,
        params[:url_input],
        class: "form-control input-home",
        placeholder: "Enter URL"
      %>
      <%= button_tag "Scrap", class: "btn-blue" %>
    <% end %>
  </div>
</div>

<% if false %>
  <%= simple_form_for :city, :url => properties_path, method: :post do |f| %>
    <%= f.input :city, label: "City" %>
   <%= f.submit "Submit", class: "btn-primary" %>
  <% end %>
<% end %>

app/views/pages/scrapping.html.erb
<p>here's the result</p>
<%= @properties %>

app/views/properties/index.html.erb
<div class="container-index-properties">
  <div class="table-responsive">
    <table class="table table-hover table-condensed" id="table-index-properties" data-toggle="table" data-sort-name="Posted on" data-sort-order="desc">
      <thead>
        <tr>
          <th scope="col">Ref</th>
          <th scope="col">City</th>
          <th scope="col">Title</th>
          <th scope="col">Rent</th>
          <th scope="col">Posted on</th>
          <th scope="col">Phone</th>
          <th scope="col">URL</th>
        </tr>
      </thead>
      <tbody>
        <% @properties.each do |property| %>
        <tr>
          <td><%= property.ref %></td>
          <td><%= property.city %></td>
          <td><%= property.title %></td>
          <td><%= number_with_delimiter(property.price, :delimiter => ',') %></td>
          <td><%= property.date.strftime('%d/%m/%y') unless property.date.nil? %></td>
          <td><%= property.phone %></td>
          <td>
            <%= link_to property.url, target: "_blank" do %>
              <i class="fas fa-external-link-alt"></i>
            <% end %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/scraps/index.html.erb
<div class="container-index-properties">
  <div class="table-responsive">
    <table class="table table-hover table-condensed" id="table-index-properties" >
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Date</th>
          <th scope="col">City</th>
          <th scope="col"># properties</th>
          <th scope="col">URL</th>
        </tr>
      </thead>
      <tbody>
        <% @scraps.each do |scrap| %>
        <tr onclick="location.href='<%= scrap_path(scrap) %>'" >
          <td><%= scrap.id %></td>
          <td><%= scrap.created_at.strftime('%d/%m/%y') %></td>
          <td><%= scrap.city %></td>
          <td><%= scrap.number %></td>
          <td><%= link_to scrap.scrap_url, target: "_blank" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/scraps/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,90,146,0.3) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "banner-home.jpg" %>);">
  <div class="banner-content">
    <h1>Scrap me !</h1>
    <p>Get in touch with owners quickly</p>
    <%= simple_form_for @scrap, html: {class: "form-inline form-home"} do |f| %>
      <%= f.input :scrap_url,
                  label: false,
                  placeholder: "Enter URL",
                  autofocus: true,
                  input_html: {class: "form-control input-home"} %>
      <%= f.submit "Submit", class: "btn-blue" %>
    <% end %>
  </div>
</div>

<% if false %>
  <%= simple_form_for :city, :url => properties_path, method: :post do |f| %>
    <%= f.input :city, label: "City" %>
   <%= f.submit "Submit", class: "btn-primary" %>
  <% end %>
<% end %>

app/views/scraps/show.html.erb
<div class="container-index-properties">
  <div class="flex-h-simple" style="margin-bottom: 24px;">
    <h3 style="margin-right: 32px; margin-bottom: 0px; margin-top: 0px;"><%= @properties.length %> new properties scrapped</h3>
    <%= link_to "Scrap again", root_path, class: "btn-blue btn-small" %>
  </div>
  <div class="table-responsive">
    <table class="table table-hover table-condensed" id="table-index-properties" data-toggle="table" data-sort-name="Posted on" data-sort-order="desc">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">City</th>
          <th scope="col">Title</th>
          <th scope="col">Rent</th>
          <th scope="col">Posted on</th>
          <th scope="col">Phone</th>
          <th scope="col">URL</th>
        </tr>
      </thead>
      <tbody>
        <% @properties.each do |property| %>
        <tr>
          <td><%= property.id %></td>
          <td><%= property.city %></td>
          <td><%= property.title %></td>
          <td><%= number_with_delimiter(property.price, :delimiter => ',') %></td>
          <td><%= property.date %></td>
          <td><%= property.phone %></td>
          <td>
            <%= link_to property.url, target: "_blank" do %>
              <i class="fas fa-external-link-alt"></i>
            <% end %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My properties", properties_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My scraps", scraps_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "user1.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <% if current_user.admin? %>
                <%= link_to admin_root_path do %>
                  <i class="fas fa-columns"></i>  <%= t(".dashboard", default: "Dashboard") %>
                <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/urls/create.html.erb
<h1>Urls#create</h1>
<p>Find me in app/views/urls/create.html.erb</p>

app/views/urls/index.html.erb
<h1>Urls#index</h1>
<p>Find me in app/views/urls/index.html.erb</p>

app/views/urls/new.html.erb
<h1>Urls#new</h1>
<p>Find me in app/views/urls/new.html.erb</p>